# This file is the entry point to configure the routes for your dependencies.
uvdesk_support_center_bundle_member_routing_resources:
    resource: "routes/private-agents.yaml"
    prefix:   /{_locale}/%uvdesk_site_path.member_prefix%/
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'

uvdesk_support_center_bundle_customer_routing_resources:
    resource: "routes/private-customers.yaml"
    prefix:   /{_locale}/%uvdesk_site_path.knowledgebase_customer_prefix%/
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'

uvdesk_support_center_bundle_public_routing_resources:
    resource: "routes/public.yaml"
    prefix:   /{_locale}/
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'
