security:
    firewalls:
        customer:
            pattern: /customer
            provider: user_provider
            anonymous: ~
            form_login:
                use_referer: true
                login_path: helpdesk_customer_login
                check_path: helpdesk_customer_login
                default_target_path: helpdesk_customer_ticket_collection
                always_use_default_target_path: true
            logout:
                path: helpdesk_customer_logout
                target: helpdesk_customer_login

    access_control:
        - { path: /customer/login, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: /customer/create-ticket, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: /customer/forgot-password, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: /customer/update-credentials, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: /customer/, roles: ROLE_CUSTOMER }
